export const ESTABLISH_CONNECTION = 'ESTABLISH_CONNECTION';
export const CONNECT_PLAYER = 'CONNECT_PLAYER';
export const JOIN_PLAYER = 'JOIN_PLAYER';

export const SET_CURRENT_CELL = 'SET_CURRENT_CELL';
