//STATUS
export const CONNECT_STAGE = 'CONNECT_STAGE';
export const SETTING_STAGE = 'SETTING_STAGE';
export const MATCHMAKING_STAGE = 'MATCHMAKING_STAGE';
export const GAME_STAGE = 'GAME_STAGE';

//CONNECT
export const ESTABLISH_CONNECTION = 'ESTABLISH_CONNECTION';
export const CONNECT_PLAYER = 'CONNECT_PLAYER';

//SETTING
export const SET_SHIP = 'SET_SHIP';
export const UNSET_SHIP = 'UNSET_SHIP';
export const RANDOMIZE_BOARD = 'RANDOMIZE_BOARD';
export const RESET_BOARD = 'RESET_BOARD';

//GAME
export const SET_GAME_BOARDS = 'SET_GAME_BOARDS';
export const UNSET_GAME_BOARDS = 'UNSET_GAME_BOARDS';
export const SET_TURN_ID = 'SET_TURN_ID';
